# Generated by Django 5.0.3 on 2024-04-11 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characteristic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'Характеристика', 'verbose_name_plural': 'Характеристика'},
        ),
        migrations.AlterModelOptions(
            name='subfeature',
            options={'verbose_name': 'Подхарактеристика', 'verbose_name_plural': 'Подхарактеристика'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='subfeature',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_feature', to='characteristic.feature', verbose_name='Характеристика'),
        ),
    ]
