version: "3.12"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - "./pg_data:/var/lib/postgresql/data"


  django_musical_store:
    image: musical_store:0.1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: musical_store
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: db
    depends_on:
      - db
    volumes:
      - "./media:/app/media"
    command: /bin/sh run.sh


  nginx:
    image: nginx:1.25.4-alpine
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - "./service/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./static:/var/www/static:ro"
      - "./media:/var/www/media:ro"
    depends_on:
      - django_musical_store