# Generated by Django 5.0.3 on 2024-04-05 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characteristic', '0001_initial'),
        ('common_models', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsubfeature',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='productsubfeature',
            name='sub_feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristic.subfeature'),
        ),
        migrations.AlterUniqueTogether(
            name='productsubfeature',
            unique_together={('product', 'sub_feature')},
        ),
    ]
