# Generated by Django 5.0.3 on 2024-04-11 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productsubfeature',
            unique_together=set(),
        ),
    ]
