# Generated by Django 5.0.3 on 2024-05-12 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsubfeature',
            options={'verbose_name': 'Характеристика товара', 'verbose_name_plural': 'Характеристики товаров'},
        ),
    ]
