# Generated by Django 5.0.3 on 2024-04-11 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_addressuser'),
        ('card', '0003_deliveryman_order_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.addressuser', verbose_name='Адрес доставки'),
        ),
    ]
